CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    auth_provider VARCHAR(30) NOT NULL DEFAULT 'LOCAL',
    provider_user_id VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_auth_provider CHECK (auth_provider IN ('LOCAL', 'GOOGLE', 'GITHUB'))
);

CREATE UNIQUE INDEX uq_users_provider_user_id
    ON users (auth_provider, provider_user_id)
    WHERE provider_user_id IS NOT NULL;

CREATE TABLE job_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_job_roles_role_code UNIQUE (role_code),
    CONSTRAINT uq_job_roles_role_name UNIQUE (role_name)
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_role_id BIGINT NOT NULL,
    current_level VARCHAR(30) NOT NULL,
    weekly_study_hours SMALLINT,
    target_date DATE,
    interest_areas_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    resume_asset_id BIGINT,
    portfolio_asset_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_profiles_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_profiles_job_role_id FOREIGN KEY (job_role_id) REFERENCES job_roles (id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_profiles_current_level CHECK (current_level IN ('BEGINNER', 'BASIC', 'JUNIOR', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT ck_user_profiles_weekly_study_hours CHECK (weekly_study_hours IS NULL OR weekly_study_hours BETWEEN 1 AND 40)
);

CREATE TABLE skill_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_role_id BIGINT NOT NULL,
    skill_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    importance SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_skill_requirements_job_role_id FOREIGN KEY (job_role_id) REFERENCES job_roles (id) ON DELETE RESTRICT,
    CONSTRAINT uq_skill_requirements_role_skill UNIQUE (job_role_id, skill_name),
    CONSTRAINT ck_skill_requirements_importance CHECK (importance BETWEEN 1 AND 5)
);

CREATE INDEX idx_skill_requirements_role_category
    ON skill_requirements (job_role_id, category);

CREATE TABLE user_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    skill_name VARCHAR(100) NOT NULL,
    proficiency_level VARCHAR(30),
    source_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_user_skills_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_user_skills_user_skill_source UNIQUE (user_id, skill_name, source_type),
    CONSTRAINT ck_user_skills_proficiency_level CHECK (proficiency_level IS NULL OR proficiency_level IN ('NONE', 'BASIC', 'WORKING', 'STRONG')),
    CONSTRAINT ck_user_skills_source_type CHECK (source_type IN ('USER_INPUT', 'GITHUB_ESTIMATED', 'SYSTEM_DERIVED'))
);

CREATE INDEX idx_user_skills_user_id
    ON user_skills (user_id);

CREATE TABLE github_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    github_user_id VARCHAR(100) NOT NULL,
    github_login VARCHAR(100) NOT NULL,
    access_type VARCHAR(30) NOT NULL,
    connected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    disconnected_at TIMESTAMPTZ,
    CONSTRAINT fk_github_connections_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_github_connections_user_github_user UNIQUE (user_id, github_user_id),
    CONSTRAINT ck_github_connections_access_type CHECK (access_type IN ('OAUTH'))
);

CREATE TABLE github_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    github_connection_id BIGINT NOT NULL,
    repo_node_id VARCHAR(100),
    repo_full_name VARCHAR(200) NOT NULL,
    repo_url VARCHAR(255) NOT NULL,
    primary_language VARCHAR(50),
    default_branch VARCHAR(100),
    is_selected BOOLEAN NOT NULL DEFAULT FALSE,
    is_core_repo BOOLEAN NOT NULL DEFAULT FALSE,
    metadata_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_github_projects_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_github_projects_connection_id FOREIGN KEY (github_connection_id) REFERENCES github_connections (id) ON DELETE CASCADE,
    CONSTRAINT uq_github_projects_user_repo_full_name UNIQUE (user_id, repo_full_name)
);

CREATE INDEX idx_github_projects_connection_selected
    ON github_projects (github_connection_id, is_selected);

CREATE TABLE github_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    github_connection_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    summary TEXT NOT NULL,
    analysis_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_github_analyses_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_github_analyses_connection_id FOREIGN KEY (github_connection_id) REFERENCES github_connections (id) ON DELETE RESTRICT,
    CONSTRAINT uq_github_analyses_user_version UNIQUE (user_id, version),
    CONSTRAINT ck_github_analyses_version CHECK (version >= 1)
);

CREATE INDEX idx_github_analyses_user_created_at
    ON github_analyses (user_id, created_at DESC);

CREATE TABLE capability_diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    profile_id BIGINT NOT NULL,
    github_analysis_id BIGINT NOT NULL,
    job_role_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    current_level VARCHAR(30) NOT NULL,
    summary TEXT NOT NULL,
    diagnosis_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_capability_diagnoses_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_capability_diagnoses_profile_id FOREIGN KEY (profile_id) REFERENCES user_profiles (id) ON DELETE RESTRICT,
    CONSTRAINT fk_capability_diagnoses_github_analysis_id FOREIGN KEY (github_analysis_id) REFERENCES github_analyses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_capability_diagnoses_job_role_id FOREIGN KEY (job_role_id) REFERENCES job_roles (id) ON DELETE RESTRICT,
    CONSTRAINT uq_capability_diagnoses_user_version UNIQUE (user_id, version),
    CONSTRAINT ck_capability_diagnoses_version CHECK (version >= 1),
    CONSTRAINT ck_capability_diagnoses_current_level CHECK (current_level IN ('BEGINNER', 'BASIC', 'JUNIOR', 'INTERMEDIATE', 'ADVANCED'))
);

CREATE INDEX idx_capability_diagnoses_user_created_at
    ON capability_diagnoses (user_id, created_at DESC);

CREATE TABLE learning_roadmaps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    diagnosis_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    total_weeks SMALLINT NOT NULL,
    summary TEXT NOT NULL,
    roadmap_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_learning_roadmaps_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_learning_roadmaps_diagnosis_id FOREIGN KEY (diagnosis_id) REFERENCES capability_diagnoses (id) ON DELETE RESTRICT,
    CONSTRAINT uq_learning_roadmaps_user_version UNIQUE (user_id, version),
    CONSTRAINT ck_learning_roadmaps_version CHECK (version >= 1),
    CONSTRAINT ck_learning_roadmaps_total_weeks CHECK (total_weeks >= 1)
);

CREATE INDEX idx_learning_roadmaps_user_created_at
    ON learning_roadmaps (user_id, created_at DESC);

CREATE TABLE roadmap_weeks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id BIGINT NOT NULL,
    week_number SMALLINT NOT NULL,
    topic VARCHAR(255) NOT NULL,
    reason_text TEXT NOT NULL,
    tasks_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    materials_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    estimated_hours NUMERIC(4, 1) NOT NULL,
    CONSTRAINT fk_roadmap_weeks_roadmap_id FOREIGN KEY (roadmap_id) REFERENCES learning_roadmaps (id) ON DELETE CASCADE,
    CONSTRAINT uq_roadmap_weeks_roadmap_week_number UNIQUE (roadmap_id, week_number),
    CONSTRAINT ck_roadmap_weeks_week_number CHECK (week_number >= 1),
    CONSTRAINT ck_roadmap_weeks_estimated_hours CHECK (estimated_hours > 0)
);

CREATE INDEX idx_roadmap_weeks_roadmap_id
    ON roadmap_weeks (roadmap_id);

CREATE TABLE progress_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    roadmap_week_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    note TEXT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_progress_logs_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_logs_roadmap_week_id FOREIGN KEY (roadmap_week_id) REFERENCES roadmap_weeks (id) ON DELETE CASCADE,
    CONSTRAINT ck_progress_logs_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE', 'SKIPPED'))
);

CREATE INDEX idx_progress_logs_user_week_created_at
    ON progress_logs (user_id, roadmap_week_id, created_at DESC);

CREATE INDEX idx_progress_logs_user_created_at
    ON progress_logs (user_id, created_at DESC);
