-- ============================================================
-- V5__v2_coach_context_schema.sql
-- v2 Context Manager / Coach / Pattern Detector 테이블 추가
-- ============================================================

-- ------------------------------------------------------------
-- user_context_snapshots
-- Context Manager가 조립한 읽기용 snapshot.
-- PROFILE / PLAN / CONVERSATION 세 종류.
-- active row는 context_type별로 valid_to IS NULL인 row 1개.
-- ------------------------------------------------------------
CREATE TABLE user_context_snapshots (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    context_type VARCHAR(30) NOT NULL,
    version     INTEGER      NOT NULL,
    payload     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    valid_from  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    valid_to    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_ucs_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_ucs_user_type_version
        UNIQUE (user_id, context_type, version),
    CONSTRAINT ck_ucs_context_type
        CHECK (context_type IN ('PROFILE', 'PLAN', 'CONVERSATION')),
    CONSTRAINT ck_ucs_version_positive
        CHECK (version >= 1)
);

CREATE INDEX idx_ucs_user_type_active
    ON user_context_snapshots (user_id, context_type)
    WHERE valid_to IS NULL;

CREATE INDEX idx_ucs_user_type_version
    ON user_context_snapshots (user_id, context_type, version DESC);


-- ------------------------------------------------------------
-- chat_sessions
-- Coach 세션. 시작 시점의 snapshot version을 고정한다.
-- profile_version / roadmap_version은 원본 result version이 아니라
-- user_context_snapshots.version을 가리킨다.
-- ------------------------------------------------------------
CREATE TABLE chat_sessions (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL,
    profile_version  INTEGER     NOT NULL,
    roadmap_version  INTEGER     NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at         TIMESTAMPTZ,

    CONSTRAINT fk_cs_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_cs_status
        CHECK (status IN ('ACTIVE', 'CLOSED')),
    CONSTRAINT ck_cs_profile_version_positive
        CHECK (profile_version >= 1),
    CONSTRAINT ck_cs_roadmap_version_positive
        CHECK (roadmap_version >= 1)
);

CREATE INDEX idx_cs_user_started_at
    ON chat_sessions (user_id, started_at DESC);


-- ------------------------------------------------------------
-- coach_conversations
-- 세션 내 메시지 이력. USER / COACH 교대 append-only.
-- ------------------------------------------------------------
CREATE TABLE coach_conversations (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT      NOT NULL,
    user_id         BIGINT      NOT NULL,
    role            VARCHAR(10) NOT NULL,
    message_text    TEXT        NOT NULL,
    route           VARCHAR(30),
    detected_intent VARCHAR(50),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_cc_session_id
        FOREIGN KEY (session_id) REFERENCES chat_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_cc_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_cc_role
        CHECK (role IN ('USER', 'COACH')),
    CONSTRAINT ck_cc_route
        CHECK (route IS NULL OR route IN (
            'SIMPLE_GUIDE', 'REPLAN_SUGGEST', 'REPLAN_EXECUTE', 'DISMISS'
        ))
);

CREATE INDEX idx_cc_session_created_at
    ON coach_conversations (session_id, created_at);


-- ------------------------------------------------------------
-- replan_proposals
-- Coach가 재계획을 제안할 때 생성. 사용자 확인 전까지 pending.
-- confirmed / dismissed / expired 중 하나로 종료된다.
-- ------------------------------------------------------------
CREATE TABLE replan_proposals (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    message_id  BIGINT,
    reason      TEXT        NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expires_at  TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_rp_session_id
        FOREIGN KEY (session_id) REFERENCES chat_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_message_id
        FOREIGN KEY (message_id) REFERENCES coach_conversations (id) ON DELETE SET NULL,
    CONSTRAINT ck_rp_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'DISMISSED', 'EXPIRED'))
);

CREATE INDEX idx_rp_session_status
    ON replan_proposals (session_id, status);

CREATE INDEX idx_rp_user_pending
    ON replan_proposals (user_id, expires_at)
    WHERE status = 'PENDING';


-- ------------------------------------------------------------
-- detected_patterns
-- Pattern Detector(SQL 배치)가 감지한 사용자 행동 패턴.
-- LLM을 호출하지 않는다.
-- processed_at이 NULL이면 미처리(activeSignals 후보).
-- ------------------------------------------------------------
CREATE TABLE detected_patterns (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    pattern_type VARCHAR(50) NOT NULL,
    severity     VARCHAR(20) NOT NULL,
    metadata     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    processed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_dp_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_dp_pattern_type
        CHECK (pattern_type IN (
            'REPEATED_INCOMPLETE',
            'CONSECUTIVE_DELAY',
            'SKILL_REPEATED_FAILURE',
            'GOAL_DRIFT_CANDIDATE'
        )),
    CONSTRAINT ck_dp_severity
        CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE INDEX idx_dp_user_unprocessed
    ON detected_patterns (user_id, created_at DESC)
    WHERE processed_at IS NULL;

CREATE INDEX idx_dp_user_pattern_type
    ON detected_patterns (user_id, pattern_type);


-- ------------------------------------------------------------
-- agent_events
-- 명시 요청 이벤트만 저장 (사용자가 Coach에게 재계획/재분석 요청).
-- Pattern Detector는 이 테이블을 사용하지 않는다.
-- ------------------------------------------------------------
CREATE TABLE agent_events (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    session_id   BIGINT,
    source_agent VARCHAR(30) NOT NULL,
    target_agent VARCHAR(30),
    event_type   VARCHAR(50) NOT NULL,
    event_data   JSONB       NOT NULL DEFAULT '{}'::jsonb,
    processed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_ae_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ae_session_id
        FOREIGN KEY (session_id) REFERENCES chat_sessions (id) ON DELETE SET NULL,
    CONSTRAINT ck_ae_source_agent
        CHECK (source_agent IN ('COACH', 'PLANNER', 'ANALYZER', 'SYSTEM')),
    CONSTRAINT ck_ae_event_type
        CHECK (event_type IN ('REPLAN_REQUESTED', 'REANALYSIS_REQUESTED'))
);

CREATE INDEX idx_ae_user_created_at
    ON agent_events (user_id, created_at DESC);

CREATE INDEX idx_ae_unprocessed
    ON agent_events (event_type, created_at DESC)
    WHERE processed_at IS NULL;
